In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
players = pd.read_csv('epl_players.csv')

In [3]:
players

,player_id,birthday,height,weight,date,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,155782,12/15/1989 0:00,170.18,146.0,4/21/2016 0:00,left,high,medium,80.0,53.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
1,155782,12/15/1989 0:00,170.18,146.0,04/07/2016 0:00,left,high,medium,80.0,53.0,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
2,155782,12/15/1989 0:00,170.18,146.0,01/07/2016 0:00,left,high,medium,79.0,52.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
3,155782,12/15/1989 0:00,170.18,146.0,12/24/2015 0:00,left,high,medium,79.0,51.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
4,155782,12/15/1989 0:00,170.18,146.0,12/17/2015 0:00,left,high,medium,79.0,51.0,...,65.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32728,35506,10/06/1981 0:00,185.42,172.0,8/30/2009 0:00,right,NaN,_0,48.0,43.0,...,63.0,70.0,70.0,74.0,65.0,14.0,25.0,51.0,25.0,25.0
32729,35506,10/06/1981 0:00,185.42,172.0,2/22/2009 0:00,right,NaN,_0,48.0,43.0,...,63.0,70.0,70.0,74.0,65.0,14.0,25.0,51.0,25.0,25.0
32730,35506,10/06/1981 0:00,185.42,172.0,8/30/2008 0:00,right,NaN,_0,48.0,43.0,...,63.0,70.0,76.0,78.0,65.0,14.0,25.0,51.0,25.0,25.0
32731,35506,10/06/1981 0:00,185.42,172.0,8/30/2007 0:00,right,NaN,_0,48.0,43.0,...,63.0,70.0,76.0,78.0,65.0,14.0,25.0,51.0,25.0,25.0
32732,35506,10/06/1981 0:00,185.42,172.0,2/22/2007 0:00,right,NaN,_0,38.0,43.0,...,63.0,72.0,79.0,84.0,65.0,14.0,9.0,48.0,7.0,11.0

In [4]:
for col in players.columns:
    print(f" {col} has missing values: {players[col].isna().any()}")

 player_id has missing values: False
 birthday has missing values: True
 height has missing values: True
 weight has missing values: True
 date has missing values: False
 preferred_foot has missing values: True
 attacking_work_rate has missing values: True
 defensive_work_rate has missing values: True
 crossing has missing values: True
 finishing has missing values: True
 heading_accuracy has missing values: True
 short_passing has missing values: True
 volleys has missing values: True
 dribbling has missing values: True
 curve has missing values: True
 free_kick_accuracy has missing values: True
 long_passing has missing values: True
 ball_control has missing values: True
 acceleration has missing values: True
 sprint_speed has missing values: True
 agility has missing values: True
 reactions has missing values: True
 balance has missing values: True
 shot_power has missing values: True
 jumping has missing values: True
 stamina has missing values: True
 strength has missing values: True
 long_shots has missing values: True
 aggression has missing values: True
 interceptions has missing values: True
 positioning has missing values: True
 vision has missing values: True
 penalties has missing values: True
 marking has missing values: True
 standing_tackle has missing values: True
 sliding_tackle has missing values: True
 gk_diving has missing values: True
 gk_handling has missing values: True
 gk_kicking has missing values: True
 gk_positioning has missing values: True
 gk_reflexes has missing values: True

In [5]:
players = players[["player_id", "finishing", "dribbling", "acceleration", "sprint_speed", "positioning", "shot_power", "short_passing", "long_passing", "vision", "dribbling", "crossing", "ball_control", "marking", "standing_tackle", "sliding_tackle", "interceptions", "gk_diving", "gk_handling", "gk_kicking", "gk_positioning", "gk_reflexes", "date"]]

In [6]:
players.shape

(32733, 23)

In [7]:
players = players.dropna()

In [8]:
players.shape

(32453, 23)

In [9]:
players['date'] = pd.to_datetime(players['date'], errors='coerce')

players = players[(players['date'].dt.year == 2015) |
                           ((players['date'].dt.year == 2014) & (players['date'].dt.month == 12))]

players = players.sort_values(by=['player_id', 'date'], ascending=[True, False])

players = players.drop_duplicates(subset=['player_id'], keep='first')

players.reset_index(drop=True, inplace=True)

In [10]:
players

,player_id,finishing,dribbling,acceleration,sprint_speed,positioning,shot_power,short_passing,long_passing,vision,...,marking,standing_tackle,sliding_tackle,interceptions,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,date
0,2802,71.0,85.0,78.0,77.0,73.0,76.0,70.0,69.0,74.0,...,42.0,47.0,36.0,49.0,13.0,16.0,9.0,9.0,7.0,2015-11-19
1,3520,71.0,76.0,70.0,74.0,76.0,71.0,77.0,75.0,81.0,...,22.0,28.0,27.0,27.0,9.0,11.0,13.0,7.0,15.0,2015-12-17
2,8922,77.0,71.0,67.0,67.0,75.0,74.0,60.0,42.0,65.0,...,12.0,13.0,11.0,29.0,6.0,12.0,8.0,12.0,7.0,2015-09-25
3,8985,59.0,55.0,51.0,54.0,52.0,81.0,72.0,68.0,68.0,...,75.0,81.0,68.0,84.0,13.0,7.0,15.0,15.0,15.0,2015-10-16
4,10491,64.0,73.0,73.0,75.0,67.0,82.0,72.0,71.0,77.0,...,52.0,43.0,33.0,41.0,10.0,16.0,8.0,8.0,12.0,2015-12-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1134,680815,29.0,33.0,49.0,40.0,27.0,49.0,42.0,33.0,36.0,...,60.0,62.0,62.0,55.0,12.0,14.0,12.0,10.0,10.0,2015-12-30
1135,693138,30.0,33.0,63.0,64.0,32.0,43.0,39.0,36.0,33.0,...,55.0,72.0,64.0,55.0,6.0,11.0,8.0,11.0,9.0,2015-11-12
1136,696365,65.0,64.0,68.0,67.0,51.0,62.0,49.0,38.0,52.0,...,18.0,20.0,20.0,12.0,11.0,6.0,15.0,7.0,14.0,2015-12-03
1137,706985,44.0,59.0,56.0,62.0,55.0,57.0,60.0,56.0,50.0,...,50.0,52.0,61.0,47.0,11.0,10.0,14.0,7.0,11.0,2015-12-30
1138,750435,57.0,58.0,64.0,62.0,56.0,57.0,60.0,54.0,58.0,...,18.0,19.0,21.0,13.0,9.0,10.0,8.0,10.0,11.0,2015-11-26

In [11]:
attacker_cols = ["finishing", "dribbling", "acceleration", "sprint_speed", "positioning", "shot_power"]
midfielder_cols = ["short_passing", "long_passing", "vision", "dribbling", "crossing", "ball_control"]
defender_cols = ["marking", "standing_tackle", "sliding_tackle", "interceptions"]
goalkeeper_cols = ["gk_diving", "gk_handling", "gk_kicking", "gk_positioning", "gk_reflexes"]


def calculate_fifa_rating(df):
    # Compute average scores for each player category
    df["Attacker_Score"] = df[attacker_cols].mean(axis=1, skipna=True)
    df["Midfielder_Score"] = df[midfielder_cols].mean(axis=1, skipna=True)
    df["Defender_Score"] = df[defender_cols].mean(axis=1, skipna=True)
    df["Goalkeeper_Score"] = df[goalkeeper_cols].mean(axis=1, skipna=True)

    # Identify the highest role for each player
    df["Best_Role"] = df[["Attacker_Score", "Midfielder_Score", "Defender_Score", "Goalkeeper_Score"]].idxmax(axis=1)

    df["FIFA_rating"] = df.apply(lambda x: x[x["Best_Role"]], axis=1)
    df['Position'] = df["Best_Role"].str.replace('_Score$', '', regex=True)

    df.drop(columns=["Attacker_Score", "Midfielder_Score", "Defender_Score", "Goalkeeper_Score", "Best_Role"], inplace=True)

    return df

players = calculate_fifa_rating(players)

players

,player_id,finishing,dribbling,acceleration,sprint_speed,positioning,shot_power,short_passing,long_passing,vision,...,sliding_tackle,interceptions,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,date,FIFA_rating,Position
0,2802,71.0,85.0,78.0,77.0,73.0,76.0,70.0,69.0,74.0,...,36.0,49.0,13.0,16.0,9.0,9.0,7.0,2015-11-19,77.857143,Attacker
1,3520,71.0,76.0,70.0,74.0,76.0,71.0,77.0,75.0,81.0,...,27.0,27.0,9.0,11.0,13.0,7.0,15.0,2015-12-17,76.857143,Midfielder
2,8922,77.0,71.0,67.0,67.0,75.0,74.0,60.0,42.0,65.0,...,11.0,29.0,6.0,12.0,8.0,12.0,7.0,2015-09-25,71.714286,Attacker
3,8985,59.0,55.0,51.0,54.0,52.0,81.0,72.0,68.0,68.0,...,68.0,84.0,13.0,7.0,15.0,15.0,15.0,2015-10-16,77.000000,Defender
4,10491,64.0,73.0,73.0,75.0,67.0,82.0,72.0,71.0,77.0,...,33.0,41.0,10.0,16.0,8.0,8.0,12.0,2015-12-17,72.857143,Midfielder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1134,680815,29.0,33.0,49.0,40.0,27.0,49.0,42.0,33.0,36.0,...,62.0,55.0,12.0,14.0,12.0,10.0,10.0,2015-12-30,59.750000,Defender
1135,693138,30.0,33.0,63.0,64.0,32.0,43.0,39.0,36.0,33.0,...,64.0,55.0,6.0,11.0,8.0,11.0,9.0,2015-11-12,61.500000,Defender
1136,696365,65.0,64.0,68.0,67.0,51.0,62.0,49.0,38.0,52.0,...,20.0,12.0,11.0,6.0,15.0,7.0,14.0,2015-12-03,63.000000,Attacker
1137,706985,44.0,59.0,56.0,62.0,55.0,57.0,60.0,56.0,50.0,...,61.0,47.0,11.0,10.0,14.0,7.0,11.0,2015-12-30,56.000000,Attacker
1138,750435,57.0,58.0,64.0,62.0,56.0,57.0,60.0,54.0,58.0,...,21.0,13.0,9.0,10.0,8.0,10.0,11.0,2015-11-26,58.857143,Attacker

In [12]:
players.shape

(1139, 25)

In [13]:
players = players.drop_duplicates()

In [14]:
players.shape

(1139, 25)

In [15]:
players = players.sort_values(by=["FIFA_rating"], ascending=[False])
players['FIFA_rating'] = players['FIFA_rating'].astype(int)

In [16]:
players

,player_id,finishing,dribbling,acceleration,sprint_speed,positioning,shot_power,short_passing,long_passing,vision,...,sliding_tackle,interceptions,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,date,FIFA_rating,Position
321,30893,95.0,93.0,91.0,93.0,93.0,94.0,81.0,72.0,81.0,...,23.0,29.0,7.0,11.0,15.0,14.0,11.0,2015-10-16,93,Attacker
477,37412,90.0,89.0,92.0,86.0,90.0,85.0,78.0,63.0,83.0,...,12.0,24.0,13.0,15.0,6.0,11.0,14.0,2015-10-16,88,Attacker
481,37459,72.0,87.0,79.0,68.0,83.0,71.0,92.0,85.0,93.0,...,29.0,41.0,1.0,1.0,1.0,1.0,1.0,2015-09-21,88,Midfielder
523,38817,88.0,87.0,90.0,85.0,91.0,90.0,79.0,61.0,80.0,...,51.0,34.0,4.0,2.0,3.0,2.0,4.0,2015-09-21,88,Attacker
727,107417,83.0,94.0,93.0,87.0,86.0,79.0,85.0,82.0,86.0,...,22.0,41.0,11.0,12.0,6.0,8.0,8.0,2015-09-25,88,Attacker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1131,611682,44.0,58.0,70.0,62.0,50.0,49.0,62.0,57.0,54.0,...,61.0,54.0,13.0,6.0,9.0,6.0,12.0,2015-12-10,56,Defender
259,27372,63.0,44.0,44.0,38.0,75.0,77.0,43.0,33.0,32.0,...,38.0,47.0,13.0,11.0,14.0,5.0,10.0,2015-02-20,55,Attacker
330,30953,63.0,61.0,32.0,34.0,64.0,70.0,57.0,28.0,57.0,...,20.0,44.0,11.0,12.0,15.0,9.0,15.0,2015-04-10,55,Attacker
1111,515338,35.0,46.0,77.0,79.0,55.0,40.0,51.0,51.0,44.0,...,52.0,48.0,14.0,12.0,15.0,13.0,8.0,2015-12-10,54,Attacker
107,23934,59.0,42.0,35.0,29.0,64.0,64.0,63.0,49.0,64.0,...,43.0,37.0,8.0,15.0,13.0,6.0,7.0,2015-04-10,53,Midfielder

In [17]:
players.to_csv('sorted_players.csv', index=False)